/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedVarslerRouteImport } from './routes/_authenticated/varsler'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOppdagRouteImport } from './routes/_authenticated/oppdag'
import { Route as AuthenticatedMeldingerRouteImport } from './routes/_authenticated/meldinger'
import { Route as AuthenticatedMeldingerIndexRouteImport } from './routes/_authenticated/meldinger.index'
import { Route as AuthenticatedUUsernameRouteImport } from './routes/_authenticated/u.$username'
import { Route as AuthenticatedPostPostIdRouteImport } from './routes/_authenticated/post.$postId'
import { Route as AuthenticatedMeldingerConversationIdRouteImport } from './routes/_authenticated/meldinger.$conversationId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVarslerRoute = AuthenticatedVarslerRouteImport.update({
  id: '/varsler',
  path: '/varsler',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOppdagRoute = AuthenticatedOppdagRouteImport.update({
  id: '/oppdag',
  path: '/oppdag',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeldingerRoute = AuthenticatedMeldingerRouteImport.update({
  id: '/meldinger',
  path: '/meldinger',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeldingerIndexRoute =
  AuthenticatedMeldingerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMeldingerRoute,
  } as any)
const AuthenticatedUUsernameRoute = AuthenticatedUUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPostPostIdRoute = AuthenticatedPostPostIdRouteImport.update({
  id: '/post/$postId',
  path: '/post/$postId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeldingerConversationIdRoute =
  AuthenticatedMeldingerConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AuthenticatedMeldingerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/meldinger': typeof AuthenticatedMeldingerRouteWithChildren
  '/oppdag': typeof AuthenticatedOppdagRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/varsler': typeof AuthenticatedVarslerRoute
  '/meldinger/$conversationId': typeof AuthenticatedMeldingerConversationIdRoute
  '/post/$postId': typeof AuthenticatedPostPostIdRoute
  '/u/$username': typeof AuthenticatedUUsernameRoute
  '/meldinger/': typeof AuthenticatedMeldingerIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/oppdag': typeof AuthenticatedOppdagRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/varsler': typeof AuthenticatedVarslerRoute
  '/': typeof AuthenticatedIndexRoute
  '/meldinger/$conversationId': typeof AuthenticatedMeldingerConversationIdRoute
  '/post/$postId': typeof AuthenticatedPostPostIdRoute
  '/u/$username': typeof AuthenticatedUUsernameRoute
  '/meldinger': typeof AuthenticatedMeldingerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/meldinger': typeof AuthenticatedMeldingerRouteWithChildren
  '/_authenticated/oppdag': typeof AuthenticatedOppdagRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/varsler': typeof AuthenticatedVarslerRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/meldinger/$conversationId': typeof AuthenticatedMeldingerConversationIdRoute
  '/_authenticated/post/$postId': typeof AuthenticatedPostPostIdRoute
  '/_authenticated/u/$username': typeof AuthenticatedUUsernameRoute
  '/_authenticated/meldinger/': typeof AuthenticatedMeldingerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/meldinger'
    | '/oppdag'
    | '/profile'
    | '/varsler'
    | '/meldinger/$conversationId'
    | '/post/$postId'
    | '/u/$username'
    | '/meldinger/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/oppdag'
    | '/profile'
    | '/varsler'
    | '/'
    | '/meldinger/$conversationId'
    | '/post/$postId'
    | '/u/$username'
    | '/meldinger'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/meldinger'
    | '/_authenticated/oppdag'
    | '/_authenticated/profile'
    | '/_authenticated/varsler'
    | '/_authenticated/'
    | '/_authenticated/meldinger/$conversationId'
    | '/_authenticated/post/$postId'
    | '/_authenticated/u/$username'
    | '/_authenticated/meldinger/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/varsler': {
      id: '/_authenticated/varsler'
      path: '/varsler'
      fullPath: '/varsler'
      preLoaderRoute: typeof AuthenticatedVarslerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oppdag': {
      id: '/_authenticated/oppdag'
      path: '/oppdag'
      fullPath: '/oppdag'
      preLoaderRoute: typeof AuthenticatedOppdagRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meldinger': {
      id: '/_authenticated/meldinger'
      path: '/meldinger'
      fullPath: '/meldinger'
      preLoaderRoute: typeof AuthenticatedMeldingerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meldinger/': {
      id: '/_authenticated/meldinger/'
      path: '/'
      fullPath: '/meldinger/'
      preLoaderRoute: typeof AuthenticatedMeldingerIndexRouteImport
      parentRoute: typeof AuthenticatedMeldingerRoute
    }
    '/_authenticated/u/$username': {
      id: '/_authenticated/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof AuthenticatedUUsernameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/post/$postId': {
      id: '/_authenticated/post/$postId'
      path: '/post/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof AuthenticatedPostPostIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meldinger/$conversationId': {
      id: '/_authenticated/meldinger/$conversationId'
      path: '/$conversationId'
      fullPath: '/meldinger/$conversationId'
      preLoaderRoute: typeof AuthenticatedMeldingerConversationIdRouteImport
      parentRoute: typeof AuthenticatedMeldingerRoute
    }
  }
}

interface AuthenticatedMeldingerRouteChildren {
  AuthenticatedMeldingerConversationIdRoute: typeof AuthenticatedMeldingerConversationIdRoute
  AuthenticatedMeldingerIndexRoute: typeof AuthenticatedMeldingerIndexRoute
}

const AuthenticatedMeldingerRouteChildren: AuthenticatedMeldingerRouteChildren =
  {
    AuthenticatedMeldingerConversationIdRoute:
      AuthenticatedMeldingerConversationIdRoute,
    AuthenticatedMeldingerIndexRoute: AuthenticatedMeldingerIndexRoute,
  }

const AuthenticatedMeldingerRouteWithChildren =
  AuthenticatedMeldingerRoute._addFileChildren(
    AuthenticatedMeldingerRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMeldingerRoute: typeof AuthenticatedMeldingerRouteWithChildren
  AuthenticatedOppdagRoute: typeof AuthenticatedOppdagRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedVarslerRoute: typeof AuthenticatedVarslerRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedPostPostIdRoute: typeof AuthenticatedPostPostIdRoute
  AuthenticatedUUsernameRoute: typeof AuthenticatedUUsernameRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMeldingerRoute: AuthenticatedMeldingerRouteWithChildren,
  AuthenticatedOppdagRoute: AuthenticatedOppdagRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedVarslerRoute: AuthenticatedVarslerRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPostPostIdRoute: AuthenticatedPostPostIdRoute,
  AuthenticatedUUsernameRoute: AuthenticatedUUsernameRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
